---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - example.sk.com.my.domain
  resources:
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.sk.com.my.domain
  resources:
  - stacks/finalizers
  verbs:
  - update
- apiGroups:
  - example.sk.com.my.domain
  resources:
  - stacks/status
  verbs:
  - get
  - patch
  - update
