# permissions for end users to view stacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-sample
    app.kubernetes.io/managed-by: kustomize
  name: stack-viewer-role
rules:
- apiGroups:
  - example.sk.com.my.domain
  resources:
  - stacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.sk.com.my.domain
  resources:
  - stacks/status
  verbs:
  - get
