apiVersion: example.sk.com.my.domain/v1
kind: Stack
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-sample
    app.kubernetes.io/managed-by: kustomize
  name: stack-sample
spec:
  # TODO(user): Add fields here
